name: Run LangChain Titanic Agent

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run LangChain script
        env:  # ✅ Correct location for secret
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "✅ API key received: $OPENAI_API_KEY"  # Debug (remove later)
          python langtitan.py
