name: langtitan
channels:
  - defaults
  - conda-forge
  - pip

dependencies:
  - python=3.10
  - pandas=2.2.2
  - pip
  - pip:
      - openai==1.30.1
      - langchain==0.1.17
      - langchain-experimental==0.0.51
      - python-dotenv==1.0.1
      - tqdm==4.66.4
